require('dotenv').config();

const PORT = process.env.PORT;
const ENVIRONMENT = process.env.ENVIRONMENT;
CONNECTION_STRING = process.env.CONNECTION_STRING;
SECRET = process.env.SECRET;
BASEURL = process.env.BASEURL;
CLIENTID =  process.env.CLIENTID;
ISSUERBASEASEURL =  process.env.ISSUERBASEASEURL;
SESSION_SECRET = process.env.SESSION_SECRET;

module.exports = { PORT, ENVIRONMENT, CONNECTION_STRING, SECRET, BASEURL, CLIENTID, ISSUERBASEASEURL, SESSION_SECRET};
